all: one two three four

one: calc_formulae.c calc_error.c
	gcc -O0 -Wall -o one calc_formulae.c calc_error.c
two: calc_formulae2.c calc_error.c
	gcc -O0 -Wall -o two calc_formulae2.c calc_error.c
three: calc_formulae3.c calc_error.c
	gcc -O0 -Wall -o three calc_formulae3.c calc_error.c
four: calc_formulae4.c calc_error.c
	gcc -O0 -Wall -o four calc_formulae4.c calc_error.c
