SRC= .
UTIL = .
BUILD= .
all: fifth temp

temp: $(SRC)/temp.c $(UTIL)/utils.c
	gcc -O0 -Wall -o $(BUILD)/temp $(SRC)/temp.c $(UTIL)/utils.c
fifth: $(SRC)/calc_formulae5.c $(UTIL)/utils.c
	gcc -O0 -Wall -o $(BUILD)/fifth $(SRC)/calc_formulae5.c $(UTIL)/utils.c
