SRC= .
UTIL = .
BUILD= .
all: fifth 

temp: $(SRC)/temp.c $(UTIL)/utils.c $(UTIL)/list.c
	gcc -O0 -Wall -o $(BUILD)/temp $(SRC)/temp.c $(UTIL)/utils.c $(UTIL)/list.c
fifth: $(SRC)/calc_formulae5.c $(UTIL)/utils.c $(UTIL)/list.c
	gcc -O0 -Wall -o $(BUILD)/fifth $(SRC)/calc_formulae5.c $(UTIL)/utils.c $(UTIL)/list.c
