SRC= .
UTIL = .
BUILD= .
all: fifth

one: $(SRC)/calc_formulae.c $(UTIL)/utils.c
	gcc -O0 -Wall -o $(BUILD)/one $(SRC)/calc_formulae.c $(UTIL)/utils.c
two: $(SRC)/calc_formulae2.c $(UTIL)/utils.c
	gcc -O0 -Wall -o $(BUILD)/two $(SRC)/calc_formulae2.c $(UTIL)/utils.c
three: $(SRC)/calc_formulae3.c $(UTIL)/utils.c
	gcc -O0 -Wall -o $(BUILD)/three $(SRC)/calc_formulae3.c $(UTIL)/utils.c
four: $(SRC)/calc_formulae4.c $(UTIL)/utils.c
	gcc -O0 -Wall -o $(BUILD)/four $(SRC)/calc_formulae4.c $(UTIL)/utils.c
fifth: $(SRC)/calc_formulae5.c $(UTIL)/utils.c
	gcc -O0 -Wall -o $(BUILD)/fifth $(SRC)/calc_formulae5.c $(UTIL)/utils.c
